### ISSUE TITLE
Error while processing procedure postDialogWebhook: Cannot use 'in' operator to search for 'typeName' in undefined

### ISSUE THREAD

**Issue by chinesehemp** [calasanmarko/trpc-swift#1]
Firstly, thank you for creating this. I'm building my first Swift app, and I'm trying to connect it to my existing TRPC server used by my PWA, so code gen like this is super helpful to me when porting the PWA to iOS.

Second, I've got a procedure that returns void, and I'm getting the following error when trying to code gen. Do you know how I can fix it?

`Error while processing procedure postDialogWebhook: Cannot use 'in' operator to search for 'typeName' in undefined`

```typescript
import { TRPCError } from "@trpc/server";
import { logger } from "firebase-functions/v1";
import { Event } from "stream-chat";
import { z } from "zod";
import { dialogWebhookProcedure } from "../server/trpc";

// type DialogWebhookMutationInput = RouterInput["postDialogWebhook"];

export const dialogWebhookMutation = dialogWebhookProcedure
  .input((value): Event => {
    return value as Event;
  })
  .output(z.void())
  .mutation(async (opts) => {
    try {
      logger.log(opts);
      return;
    } catch (err: any) {
      logger.error("dialogWebhookMutation err", err);
      throw new TRPCError({ message: err.message, code: err.code });
    }
  });
```

**Comment by calasanmarko** [comment]
Hey, I'm glad somebody found this useful, and I'm sorry for the delayed response, in fact I never noticed the issue until now.

The error occurs because you're using a custom validator for your input, whereas this library only supports validation using Zod. I realize that I've never mentioned this in the documentation, which I will now update accordingly.

Thanks for your input.
